Fix player compilation, implement basic new_job

diff --git a/supervisor/lxc_share/make_player b/supervisor/lxc_share/make_player
--- a/supervisor/lxc_share/make_player
+++ b/supervisor/lxc_share/make_player
@@ -9,24 +9,33 @@ EOF
     exit
 fi
 
+# lxc doesn't export the PATH to our child processes
+export PATH
+
 env_id=$1
 automake=$2
+
+out=/make_player.log
+touch $out
+chmod 666 $out
 
 cd /root
 num_files=$(ls | wc -l)
 if ! [ $num_files -eq 1 ]; then
     if [ $num_files -gt 1 ]; then
-        echo >&2 "Error: more than one file in /root/"
+        echo >$out "Error: more than one file in /root/"
     else
-        echo >&2 "Error: player file not found in /root/"
+        echo >$out "Error: player file not found in /root/"
     fi
     exit 1
 fi
 file=$(ls)
 
+is_archive=false
 if 7z t $file >/dev/null 2>&1; then
+    is_archive=true
     if ! 7z e $file >/dev/null 2>&1; then
-      echo >&2 "Error: failure to extract files from '$file'"
+      echo >$out "Error: failure to extract files from '$file'"
       exit 1
     fi
 fi
@@ -34,31 +43,55 @@ fi
 if [ $automake = True ]; then
     case $env_id in
       0) # C
+          echo >$out "Error: env_id '$env_id' not implemented"
+          exit 1
           ;;
       1) # C++
+          echo >$out "Error: env_id '$env_id' not implemented"
+          exit 1
           ;;
       2) # python
+          echo >$out "Error: env_id '$env_id' not implemented"
+          exit 1
           ;;
       *)
-          echo >&2 "Error: unknown env_id: '$env_id'"
+          echo >$out "Error: unknown env_id '$env_id'"
           exit 1
           ;;
     esac
+    echo >$out "OK"
     exit
 fi
 
 # no automake
-if [ -f build ]; then
-    chmod +x build
-    if ! ./build; then
-        echo >&2 "Error: running 'build' returned an error"
-        exit 1
+if ! [ -f build ]; then
+    echo >$out "Error: 'build' file not found (automake off)"
+    if [ "$is_archive" = false ]; then
+        echo >$out "Warning: uploaded file is not recognized as an archive"
     fi
+    exit 1
 fi
+
+chmod +x build
+
+if ! ./build 2>/tmp/build.log; then
+    echo >$out "Error: running 'build' returned an error"
+    echo >$out "Build logs: $(cat /tmp/build.log)"
+    exit 1
+fi
+
 if [ -f run ]; then
     chmod +x run
-    ln -s /root/run /player
+    cat >/player <<EOF
+#!/bin/sh
+export PATH
+cd root
+./run \$1 \$2 >/run.log 2>&1
+EOF
+    chmod +x /player
+    echo >$out "OK"
+    exit
 else
-    echo >&2 "Error: can't find 'run' (automake False)"
+    echo >$out "Error: can't find 'run' (automake off)"
     exit 1
 fi
